export const LANGUAGES = [
  { id: 'python', name: 'Python', icon: '🐍' },
  { id: 'cpp', name: 'C++', icon: '⚙️' },
  { id: 'java', name: 'Java', icon: '☕' },
  { id: 'javascript', name: 'JavaScript', icon: '🟨' },
  { id: 'typescript', name: 'TypeScript', icon: '🟦' },
  { id: 'csharp', name: 'C#', icon: '💜' },
  { id: 'go', name: 'Go', icon: '🔵' },
  { id: 'rust', name: 'Rust', icon: '🦀' },
  { id: 'php', name: 'PHP', icon: '🐘' },
  { id: 'ruby', name: 'Ruby', icon: '💎' },
  { id: 'swift', name: 'Swift', icon: '🍎' },
  { id: 'kotlin', name: 'Kotlin', icon: '💜' },
  { id: 'dart', name: 'Dart', icon: '🎯' },
  { id: 'r', name: 'R', icon: '📊' },
  { id: 'matlab', name: 'MATLAB', icon: '🔢' },
  { id: 'perl', name: 'Perl', icon: '🐪' },
  { id: 'scala', name: 'Scala', icon: '🔴' },
  { id: 'haskell', name: 'Haskell', icon: 'λ' },
  { id: 'lua', name: 'Lua', icon: '🌙' },
  { id: 'fortran', name: 'Fortran', icon: '📜' },
  { id: 'cobol', name: 'COBOL', icon: '📠' },
  { id: 'visualbasic', name: 'Visual Basic', icon: '🟦' },
];
